sudo: false
language: node_js
node_js:
  - "7"
cache:
  yarn: true
  directories:
    - node_modules
install:
  yarn
script:
  - yarn run lint
  - yarn run test
after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
